package vn.edu.hcmaf.apigamestore.common;

import jakarta.persistence.Column;
import jakarta.persistence.MappedSuperclass;
import jakarta.persistence.PrePersist;
import jakarta.persistence.PreUpdate;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Getter
@Setter
@MappedSuperclass
public class BaseEntity {
    @Column(name = "is_deleted", nullable = false)
    private boolean isDeleted = false;
    @Column(name = "deleted_at")
    private String deletedAt;
    @Column(name = "deleted_by")
    private String deletedBy;
    @Column(name = "created_at", nullable = false, updatable = false)
    private String createdAt;
    @Column(name = "updated_at", nullable = false)
    private String updatedAt;

    // Constructors, getters, and setters can be generated by Lombok
    @PrePersist
    protected void onCreate() {
        this.createdAt = String.valueOf(LocalDateTime.now());
        this.updatedAt = String.valueOf(LocalDateTime.now());
        this.isDeleted = false;
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = String.valueOf(LocalDateTime.now());
    }
}
